CELL 1 — Judul

In [ ]:
# ============================================================
# TUGAS DATA CLEANING
# DATA TRANSAKSI CRYPTO
# ============================================================

print("==============================================")
print("       TUGAS DATA CLEANING")
print("       DATA TRANSAKSI CRYPTO")
print("==============================================")
print("Nama : [ISI NAMA KAMU]")
print("NIM  : 2418006")
print("Kelas: [ISI KELAS KAMU]")

==============================================
       TUGAS DATA CLEANING
       DATA TRANSAKSI CRYPTO
==============================================
Nama : [ISI NAMA KAMU]
NIM  : 2418006
Kelas: [ISI KELAS KAMU]

CELL 2 — Import library

In [ ]:
import pandas as pd
import numpy as np

print("Library berhasil diimport.")

Library berhasil diimport.

CELL 3 — Upload file Excel

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving TUGAS_DATA_SET_TRANSAKSI_CRYPTO_2418006.xlsx to TUGAS_DATA_SET_TRANSAKSI_CRYPTO_2418006.xlsx

CELL 4 — Membaca data mentah

In [ ]:
file_name = "TUGAS_DATA_SET_TRANSAKSI_CRYPTO_2418006.xlsx"

data_mentah = pd.read_excel(file_name, header=None)

print("Ukuran data mentah:", data_mentah.shape)

display(data_mentah.head(10))

Ukuran data mentah: (34, 7)

     0      1          2                3       4           5          6
0  NaN    NaN        NaN              NaN     NaN         NaN        NaN
1  NaN    NaN        NaN              NaN     NaN         NaN        NaN
2  NaN    NaN        NaN              NaN     NaN         NaN        NaN
3   No  TX_ID  Nama-Aset  Jenis_Transaksi  Jumlah  Harga_USDT     Status
4    1  TX001    Bitcoin              Buy   0.002       65000  Completed
5    2  TX002   Ethereum             Sell   0.015        3200  Completed
6    3  TX003     Solana              Buy    0.50         145    Pending
7    4  TX004    Bitcoin             Sell   0.001       65500  Completed
8    5  TX005   Ethereum              Buy   0.020        3180  Completed
9    6  TX006        XRP              Buy     100        0.55    Pending

CELL 5 — Menampilkan kondisi data mentah

In [ ]:
print("Data mentah:")
display(data_mentah)

Data mentah:

      0      1          2                3       4           5          6
0   NaN    NaN        NaN              NaN     NaN         NaN        NaN
1   NaN    NaN        NaN              NaN     NaN         NaN        NaN
2   NaN    NaN        NaN              NaN     NaN         NaN        NaN
3    No  TX_ID  Nama-Aset  Jenis_Transaksi  Jumlah  Harga_USDT     Status
4     1  TX001    Bitcoin              Buy   0.002       65000  Completed
5     2  TX002   Ethereum             Sell   0.015        3200  Completed
6     3  TX003     Solana              Buy    0.50         145    Pending
7     4  TX004    Bitcoin             Sell   0.001       65500  Completed
8     5  TX005   Ethereum              Buy   0.020        3180  Completed
9     6  TX006        XRP              Buy     100        0.55    Pending
10    7  TX007     Solana             Sell    1.20         148  Completed
11    8  TX008    Cardano              Buy      50        0.42  Completed
12    9  TX009    Bitcoin              Buy   0.003       64800     Failed
13   10  TX010   Ethereum             Sell   0.025        3250  Completed
14   11  TX011        XRP              Buy     150        0.58  Completed
15   12  TX012     Solana              Buy    0.80         150  Completed
16   13  TX013    Cardano             Sell      75        0.44    Pending
17   14  TX014    Bitcoin             Sell   0.002       66000  Completed
18   15  TX015   Ethereum              Buy   0.030        3220  Completed
19   16  TX016        XRP             Sell     200        0.60  Completed
20   17  TX017     Solana              Buy    1.50         152     Failed
21   18  TX018    Cardano              Buy     100        0.43  Completed
22   19  TX019    Bitcoin              Buy   0.001       66200    Pending
23   20  TX020   Ethereum             Sell   0.010        3300  Completed
24   21  TX021        XRP              Buy     250        0.61     Failed
25   22  TX022     Solana             Sell    0.70         155  Completed
26   23  TX023    Cardano              Buy      80        0.45  Completed
27   24  TX024    Bitcoin             Sell   0.003       67000  Completed
28   25  TX025   Ethereum              Buy   0.018        3280    Pending
29   26  TX026        XRP             Sell     120        0.59  Completed
30   27  TX027     Solana              Buy    2.00         158  Completed
31   28  TX028    Cardano             Sell      60        0.46  Completed
32   29  TX029    Bitcoin              Buy   0.002       67500    Pending
33   30  TX030   Ethereum             Sell   0.022        3320  Completed

CELL 6 — Menghapus baris kosong

In [ ]:
data_mentah = data_mentah.dropna(how='all').reset_index(drop=True)

print("Data setelah baris kosong dihapus:")
display(data_mentah.head())

Data setelah baris kosong dihapus:

    0      1          2                3       4           5          6
0  No  TX_ID  Nama-Aset  Jenis_Transaksi  Jumlah  Harga_USDT     Status
1   1  TX001    Bitcoin              Buy   0.002       65000  Completed
2   2  TX002   Ethereum             Sell   0.015        3200  Completed
3   3  TX003     Solana              Buy    0.50         145    Pending
4   4  TX004    Bitcoin             Sell   0.001       65500  Completed

CELL 7 — Menentukan header yang benar

In [ ]:
data_mentah.columns = data_mentah.iloc[0]

df = data_mentah.iloc[1:].copy()

df = df.reset_index(drop=True)

print("Nama kolom:")
print(df.columns.tolist())

display(df.head())

Nama kolom:
['No', 'TX_ID', 'Nama-Aset', 'Jenis_Transaksi', 'Jumlah', 'Harga_USDT', 'Status']

0 No  TX_ID Nama-Aset Jenis_Transaksi Jumlah Harga_USDT     Status
0  1  TX001   Bitcoin             Buy  0.002      65000  Completed
1  2  TX002  Ethereum            Sell  0.015       3200  Completed
2  3  TX003    Solana             Buy   0.50        145    Pending
3  4  TX004   Bitcoin            Sell  0.001      65500  Completed
4  5  TX005  Ethereum             Buy  0.020       3180  Completed

CELL 8 — Cek informasi dataset sebelum cleaning

In [ ]:
print("===== INFORMASI DATASET =====")

print("Jumlah baris  :", df.shape[0])
print("Jumlah kolom  :", df.shape[1])

print("\nTipe data:")
print(df.dtypes)

===== INFORMASI DATASET =====
Jumlah baris  : 30
Jumlah kolom  : 7

Tipe data:
0
No                 object
TX_ID              object
Nama-Aset          object
Jenis_Transaksi    object
Jumlah             object
Harga_USDT         object
Status             object
dtype: object

CELL 9 — Cek missing value

In [ ]:
print("===== CEK MISSING VALUE =====")

missing = df.isnull().sum()

display(missing.to_frame(name="Jumlah Missing"))

===== CEK MISSING VALUE =====

                 Jumlah Missing
0
No                            0
TX_ID                         0
Nama-Aset                     0
Jenis_Transaksi               0
Jumlah                        0
Harga_USDT                    0
Status                        0

CELL 10 — Cek data duplikat

In [ ]:
print("===== CEK DATA DUPLIKAT =====")

jumlah_duplikat = df.duplicated().sum()

print("Jumlah data duplikat:", jumlah_duplikat)

if jumlah_duplikat > 0:
    display(df[df.duplicated(keep=False)])
else:
    print("Tidak terdapat data duplikat.")

===== CEK DATA DUPLIKAT =====
Jumlah data duplikat: 0
Tidak terdapat data duplikat.

CELL 11 — Membersihkan kolom teks

In [ ]:
kolom_teks = [
    'TX_ID',
    'Nama-Aset',
    'Jenis_Transaksi',
    'Status'
]

for kolom in kolom_teks:
    df[kolom] = df[kolom].astype(str).str.strip()

print("Data teks berhasil dibersihkan dari spasi berlebih.")

Data teks berhasil dibersihkan dari spasi berlebih.

CELL 12 — Mengubah tipe data angka

In [ ]:
kolom_numerik = [
    'No',
    'Jumlah',
    'Harga_USDT'
]

for kolom in kolom_numerik:
    df[kolom] = pd.to_numeric(df[kolom], errors='coerce')

print("Kolom numerik berhasil dikonversi.")

Kolom numerik berhasil dikonversi.

CELL 13 — Cek tipe data setelah cleaning

In [ ]:
print("===== TIPE DATA SETELAH CLEANING =====")

print(df.dtypes)

===== TIPE DATA SETELAH CLEANING =====
0
No                   int64
TX_ID               object
Nama-Aset           object
Jenis_Transaksi     object
Jumlah             float64
Harga_USDT         float64
Status              object
dtype: object

CELL 14 — Menghapus duplikat

In [ ]:
jumlah_sebelum = len(df)

df = df.drop_duplicates().reset_index(drop=True)

jumlah_sesudah = len(df)

print("Jumlah data sebelum :", jumlah_sebelum)
print("Jumlah data sesudah :", jumlah_sesudah)
print("Duplikat dihapus    :", jumlah_sebelum - jumlah_sesudah)

Jumlah data sebelum : 30
Jumlah data sesudah : 30
Duplikat dihapus    : 0

CELL 15 — Validasi missing value

In [ ]:
print("===== VALIDASI MISSING VALUE =====")

missing_setelah = df.isnull().sum()

display(missing_setelah.to_frame(name="Jumlah Missing"))

===== VALIDASI MISSING VALUE =====

                 Jumlah Missing
0
No                            0
TX_ID                         0
Nama-Aset                     0
Jenis_Transaksi               0
Jumlah                        0
Harga_USDT                    0
Status                        0

CELL 16 — Cek nilai unik

In [ ]:
print("===== NILAI UNIK =====")

print("\nNama Aset:")
print(df['Nama-Aset'].unique())

print("\nJenis Transaksi:")
print(df['Jenis_Transaksi'].unique())

print("\nStatus:")
print(df['Status'].unique())

===== NILAI UNIK =====

Nama Aset:
['Bitcoin' 'Ethereum' 'Solana' 'XRP' 'Cardano']

Jenis Transaksi:
['Buy' 'Sell']

Status:
['Completed' 'Pending' 'Failed']

CELL 17 — Tampilkan dataset setelah cleaning

In [ ]:
print("===== DATASET SETELAH CLEANING =====")

display(df)

===== DATASET SETELAH CLEANING =====

0   No  TX_ID Nama-Aset Jenis_Transaksi   Jumlah  Harga_USDT     Status
0    1  TX001   Bitcoin             Buy    0.002    65000.00  Completed
1    2  TX002  Ethereum            Sell    0.015     3200.00  Completed
2    3  TX003    Solana             Buy    0.500      145.00    Pending
3    4  TX004   Bitcoin            Sell    0.001    65500.00  Completed
4    5  TX005  Ethereum             Buy    0.020     3180.00  Completed
5    6  TX006       XRP             Buy  100.000        0.55    Pending
6    7  TX007    Solana            Sell    1.200      148.00  Completed
7    8  TX008   Cardano             Buy   50.000        0.42  Completed
8    9  TX009   Bitcoin             Buy    0.003    64800.00     Failed
9   10  TX010  Ethereum            Sell    0.025     3250.00  Completed
10  11  TX011       XRP             Buy  150.000        0.58  Completed
11  12  TX012    Solana             Buy    0.800      150.00  Completed
12  13  TX013   Cardano            Sell   75.000        0.44    Pending
13  14  TX014   Bitcoin            Sell    0.002    66000.00  Completed
14  15  TX015  Ethereum             Buy    0.030     3220.00  Completed
15  16  TX016       XRP            Sell  200.000        0.60  Completed
16  17  TX017    Solana             Buy    1.500      152.00     Failed
17  18  TX018   Cardano             Buy  100.000        0.43  Completed
18  19  TX019   Bitcoin             Buy    0.001    66200.00    Pending
19  20  TX020  Ethereum            Sell    0.010     3300.00  Completed
20  21  TX021       XRP             Buy  250.000        0.61     Failed
21  22  TX022    Solana            Sell    0.700      155.00  Completed
22  23  TX023   Cardano             Buy   80.000        0.45  Completed
23  24  TX024   Bitcoin            Sell    0.003    67000.00  Completed
24  25  TX025  Ethereum             Buy    0.018     3280.00    Pending
25  26  TX026       XRP            Sell  120.000        0.59  Completed
26  27  TX027    Solana             Buy    2.000      158.00  Completed
27  28  TX028   Cardano            Sell   60.000        0.46  Completed
28  29  TX029   Bitcoin             Buy    0.002    67500.00    Pending
29  30  TX030  Ethereum            Sell    0.022     3320.00  Completed

CELL 18 — Ringkasan hasil cleaning

In [ ]:
print("==============================================")
print("        HASIL DATA CLEANING")
print("==============================================")

print("Jumlah data akhir :", len(df))
print("Jumlah kolom      :", len(df.columns))
print("Jumlah duplikat   :", df.duplicated().sum())
print("Total missing     :", df.isnull().sum().sum())

print("\nKolom dataset:")
for kolom in df.columns:
    print("-", kolom)

==============================================
        HASIL DATA CLEANING
==============================================
Jumlah data akhir : 30
Jumlah kolom      : 7
Jumlah duplikat   : 0
Total missing     : 0

Kolom dataset:
- No
- TX_ID
- Nama-Aset
- Jenis_Transaksi
- Jumlah
- Harga_USDT
- Status

CELL 19 — Simpan dataset bersih

In [ ]:
nama_file_bersih = "TUGAS_DATA_SET_TRANSAKSI_CRYPTO_2418006_CLEAN.xlsx"

df.to_excel(nama_file_bersih, index=False)

print("Dataset bersih berhasil disimpan:")
print(nama_file_bersih)

Dataset bersih berhasil disimpan:
TUGAS_DATA_SET_TRANSAKSI_CRYPTO_2418006_CLEAN.xlsx

CELL 20 — Download hasil

In [ ]:
from google.colab import files

files.download(nama_file_bersih)